<a href="https://colab.research.google.com/github/MOHAMMADHOSSEIN-JAFARI/Algorithms_For_Massive_Datasets/blob/master/Neural_Netwoks_Image_Classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Neural Networks





In [20]:
# Importing Data

In [21]:
import tensorflow as tf
import numpy as np
import PIL

In [22]:
print(tf.__version__)

2.9.2


In [23]:
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.preprocessing.image import ImageDataGenerator


In [24]:
#cat_train= tf.keras.preprocessing.image_dataset_from_directory
#https://www.tensorflow.org/api_docs/python/tf/keras/utils/image_dataset_from_directory
#"https://www.youtube.com/watch?v=q7ZuZ8ZOErE"

In [25]:
#how to laod an image with tensorflow
path = '/content/drive/MyDrive/Machie_Learning_Project/0.jpg'
Load_image = tf.keras.preprocessing.image.load_img(path)
print(Load_image)


<PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=500x375 at 0x7F060333CE10>


In [26]:
#https://www.youtube.com/watch?v=oW89weRFJj8

In [27]:
type(Load_image)

PIL.JpegImagePlugin.JpegImageFile

In [28]:
print(Load_image)

<PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=500x375 at 0x7F060333CE10>


In [29]:
I = np.asarray(Load_image)


In [30]:
print(I)

[[[203 164  87]
  [203 164  87]
  [204 165  88]
  ...
  [240 201 122]
  [239 200 121]
  [238 199 120]]

 [[203 164  87]
  [203 164  87]
  [204 165  88]
  ...
  [240 201 122]
  [239 200 121]
  [239 200 121]]

 [[203 164  87]
  [203 164  87]
  [204 165  88]
  ...
  [241 202 123]
  [240 201 122]
  [239 200 121]]

 ...

 [[153 122  55]
  [153 122  55]
  [153 122  55]
  ...
  [  2   2   0]
  [  2   2   0]
  [  2   2   0]]

 [[152 121  54]
  [152 121  54]
  [152 121  54]
  ...
  [  1   1   0]
  [  1   1   0]
  [  1   1   0]]

 [[151 120  53]
  [151 120  53]
  [152 121  54]
  ...
  [  1   1   0]
  [  1   1   0]
  [  1   1   0]]]


In [31]:
#https://keras.io/api/data_loading/image/

In [32]:
from PIL import Image
img_gray = Image.open(path).convert('L')
img_gray.save('gray0.jpg')
#/content/gray0.jpg
a= np.asarray(img_gray)
print(a)



[[167 167 168 ... 204 203 202]
 [167 167 168 ... 204 203 203]
 [167 167 168 ... 205 204 203]
 ...
 [124 124 124 ...   2   2   2]
 [123 123 123 ...   1   1   1]
 [122 122 123 ...   1   1   1]]


In [33]:
import cv2

In [34]:
img = cv2.imread('/content/drive/MyDrive/Machie_Learning_Project/0.jpg')

In [35]:
res = cv2.resize(img, dsize=(54, 140), interpolation=cv2.INTER_CUBIC)

In [36]:
type(res)

numpy.ndarray

In [37]:
print(res)

[[[ 91 168 207]
  [ 99 176 215]
  [103 182 223]
  ...
  [142 217 249]
  [129 210 246]
  [121 203 244]]

 [[ 91 168 207]
  [ 99 176 215]
  [103 182 223]
  ...
  [142 217 250]
  [131 211 247]
  [124 205 243]]

 [[ 91 168 207]
  [100 177 216]
  [103 182 223]
  ...
  [143 218 250]
  [133 212 247]
  [125 206 243]]

 ...

 [[ 58 125 159]
  [ 62 129 161]
  [ 60 132 166]
  ...
  [  1   3   3]
  [  1   3   3]
  [  1   3   3]]

 [[ 57 124 155]
  [ 61 128 159]
  [ 59 131 165]
  ...
  [  1   3   3]
  [  1   3   3]
  [  1   3   3]]

 [[ 55 122 153]
  [ 60 127 158]
  [ 58 130 164]
  ...
  [  0   1   1]
  [  0   1   1]
  [  0   1   1]]]


In [38]:
from PIL import Image
img  = Image.fromarray(res)

In [39]:
img.save("Image_from_array.png")